<?php

namespace Tests;

use App\Models\LabelModel;
use App\Models\TaskModel;
use App\Models\TodoListModel;
use App\Models\UserModel;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Laravel\Sanctum\Sanctum;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->withoutExceptionHandling();
    }

    public function createUser($args = [])
    {
        return UserModel::factory()->create($args);
    }

    public function authUser()
    {
        $user = $this->createUser();
        Sanctum::actingAs($user);
        return $user;
    }

    public function createTodoList($args = [])
    {
        return TodoListModel::factory()->create($args);
    }

    public function createLabel($args = [])
    {
        return LabelModel::factory()->create($args);
    }

    public function createTask($args = [])
    {
        return TaskModel::factory()->create($args);
    }


}
